name: lasd_docs_ci


on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'lasd_docs'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'pbarch/Living_Architecture_Systems_Description'
          ref: 'master'
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: false
          path: 'Living_Architecture_Systems_Description'

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        working-directory: lasd_docs
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: lasd_docs/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
        working-directory: testbed-docs-temp
      - run: pip install mkdocs-git-revision-date-localized-plugin
        working-directory: testbed-docs-temp


      - run: mkdocs gh-deploy --config-file Living_Architecture_Systems_Description/lasd_docs/mkdocs.yml --force
        working-directory: testbed-docs-temp
